# Generated by Django 2.0.5 on 2018-09-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_color', models.CharField(max_length=1000)),
                ('background_color', models.CharField(max_length=1000)),
                ('background_image', models.CharField(max_length=1000)),
            ],
        ),
    ]
