# Generated by Django 2.0.5 on 2018-09-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_site_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_style',
            name='background_image',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
