# Generated by Django 2.0.5 on 2018-09-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_auto_20180913_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_style',
            name='background_image',
            field=models.TextField(),
        ),
    ]
