# Generated by Django 2.0.5 on 2018-09-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0005_auto_20180913_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure_Ultra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('story', models.CharField(max_length=1000)),
                ('date_thrown_away', models.DateTimeField()),
                ('foreground_image', models.FileField(upload_to='documents/')),
                ('border_color', models.CharField(max_length=1000)),
                ('font_color', models.CharField(max_length=1000)),
                ('treasure_height', models.CharField(max_length=1000)),
                ('treasure_width', models.CharField(max_length=1000)),
                ('background_color', models.CharField(max_length=1000)),
                ('background_image', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
