# Generated by Django 2.0.5 on 2018-09-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0006_treasure_ultra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure_ultra',
            name='background_image',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='treasure_ultra',
            name='foreground_image',
            field=models.TextField(),
        ),
    ]
